version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db 
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: "mysqladmin -h127.0.0.1 -P3306 -uroot -proot ping"
      interval: 2s
      timeout: 3s
      retries: 10
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8088
    volumes:
      - .:/code
    ports:
      - "8088:8088"
    depends_on:
      - db