# Generated by Django 3.1 on 2024-01-25 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://discoverjapan-web.com/wp-content/uploads/2020/08/90_main.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.post', verbose_name='大正の投稿'),
        ),
    ]
