# Generated by Django 3.1 on 2024-01-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_auto_20240126_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://discoverjapan-web.com/wp-content/uploads/2020/08/90_main.jpg', null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
