# Generated by Django 3.1 on 2024-01-30 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0007_auto_20240130_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='返信日時'),
            preserve_default=False,
        ),
    ]
